#+OPTIONS: toc:3 h:4 tags:nil todo:nil ':t ^:{}
#+LATEX_CLASS: anno-bib-times
#+LATEX_CLASS_OPTIONS: [paper=letter,oneside,DIV=8]
#+LATEX_HEADER: \usepackage[style=verbose,backend=biber]{biblatex}
#+LATEX_HEADER: \addbibresource{local.bib}
#+BIBLIOGRAPHY: local.bib
#+CITE_EXPORT: biblatex verbose
#+STARTUP: entitiespretty

#+TITLE: Guide to Radiocarbon Dating in Hawaiʻi: An Annotated Bibliography
#+AUTHOR: Thomas S. Dye
#+EMAIL: tsd at tsdye dot online
#+EXPORT_FILE_NAME: 14c-workshop-v2

* Introduction

This annotated bibliography was distributed to the attendees of the
Society for Hawaiian Archaeology's Radiocarbon Dating Workshop, which
was held at Bishop Museum on January 21, 2014. The bibliography is
organized topically, with separate sections for the general and
Hawaiian literature. It contains sources that I've found useful in my
study of radiocarbon dating and also detailed citations for the
sources of information used to construct graphics for the workshop.
The reader should be aware that many of the entries discuss a variety
of topics, so that their placement in one section or another of the
bibliography involves some choice.

* Radiocarbon Dating in General

The sources in this section are drawn from the world literature on
radiocarbon dating. They are mostly standard references that justify
the procedures used by modern radiocarbon dating programs.

** Overviews

These texts explain the theory, physics, and statistics of radiocarbon
dating and its use as evidence in historical accounts. During the
early years of radiocarbon dating, through about 1990, the radiocarbon
dating community was concerned to teach archaeologists about what goes
on in a dating laboratory, the nature of the physical processes that
make radiocarbon dating possible, and how to understand the
probabilistic nature of the dating evidence. The last 25 years have
seen more attention given to modeling the relationship of radiocarbon
dates to the other kinds of historical information available to
archaeologists. This is the subject of Bayesian calibration.

**** [cite//b: @polach88:_radioc_datin_liter_first_years;]

There are 80 references to archaeological radiocarbon dating in
Oceania, two of which are from Hawaiʻi, in this review of the first 21
years of the radiocarbon dating literature. It is a reminder of how
little archaeologists knew about chronology at the time CRM
archaeology got its start in Hawaiʻi.

**** [cite//b: @bowman90:_radioc_datin;]

This is the best general introduction to radiocarbon dating for
archaeologists. Written by the Keeper of the Department of Scientific
Research in the British Museum, it is short at only 62 pages and
concise. Sample composition and issues of association and context are
discussed in Chapter 5, Radiocarbon and Archaeology. The book has a
good description of calibration, but it was written before the Bayesian
techniques were fully developed and is now a bit outdated.

**** [cite//b: @taylor87:_radioc_datin;]
This is a longer, very thorough, treatment written by an archaeologist
who, early in his career, had the opportunity to intern at the UCLA
Institute of Geophysics and Planetary Physics. An excellent reference
book, it is more technical and less accessible than Bowman's book.
Chapter 5, /Evaluation of Radiocarbon Data/, discusses sample
composition and issues of association and context.

**** [cite//b: @buck96:_bayes_approac_inter_archaeol_data]

This book contains the classic description of the Bayesian approach to
radiocarbon calibration, set within a rigorous mathematical discussion
of modeling in archaeology, quantification of uncertainty, and
statistical modeling. The Bayesian approach to radiocarbon calibration
is designed to permit the use of various kinds of contextual
information, such as stratigraphy, to yield age estimates that are
archaeologically interpretable. Bayesian methods provide a theoretical
bridge between the results supplied by the dating laboratory and the
other types of relative and absolute chronological information
typically collected by the archaeologist in the field and during
background research into the historical record. Chapter 9,
/Interpretation of Radiocarbon Results/, presents five case studies to
illustrate the application of Bayesian methods to practical
archaeological situations, including routine incorporation of
stratigraphic information, dating of a multi-phase sequence based on
artifact classification, and outlier detection, among others.

**** [cite//b: @bayliss09:_rollin_out_revol]

A brief history and prospect of how technological advances in
radiocarbon dating have revolutionized archaeological interpretation.
The author works for English Heritage, the government agency
responsible for archaeology in England. English Heritage was quick to
recognize the potential of routine Bayesian modeling and in 2009 there
were more than 500 sites in England where ages had been estimated
using Bayesian methods. Notes that Bayesian techniques have had
greatest impact on periods of English history where artifact
chronologies aren't well developed (like Hawaiʻi), and that the impact
of the Bayesian technology on interpretation took about 15 years to
become apparent to the archaeological community.

** Sample Composition
**** [cite//b: @stuiver-polach77]

The definition of "conventional radiocarbon age" as one that
#+attr_latex: :environment inparaenum :options (i)
 - uses 5568 as the radiocarbon half-life,
 - uses National Bureau of Standards oxalic acid to define "zero" age,
 - uses AD 1950 as the zero point from which to count radiocarbon
   time, and
 - corrects the sample to a common \delta{}^{13}C value.

**** [cite//b: @niu13:_bayes_approac_radioc_calib_curve_estim]

Outlines the Bayesian methods used to estimate the calibration curves
used by software such as =Calib=, =OxCal=, and =BCal=.

** Association and Context

The archaeological association problem was first dealt with
systematically by the Dutch archaeologist, H. T. Waterbolk. A
comprehensive framework for analyzing association and context is the
Harris matrix. As radiocarbon dating techniques advanced and it became
possible to date ever smaller samples, archaeologists learned to pay
closer attention to association and context.

**** [cite//b: @waterbolk71:_workin_radioc_dates]

Waterbolk was one of the first archaeologists to think through the
problems of archaeological dating with radiocarbon. The following
quote was his motivation for publishing this article.

#+begin_quote
C-14 datings can not only provide us with estimates of the absolute
age of objects or occupation layers, but also, when available in
sufficient numbers, with initial and terminal datings for cultural
phases, thus defining their duration.
#+end_quote

Waterbolk considered it axiomatic that the dated event was always
older than its archaeological context.

#+begin_quote
A C-14 sample always has, unless contaminated with younger material,
a date older than that at which it was buried in the ground and became
associated with other objects.
#+end_quote

He noted that the dated event had to be associated with the reference
event.
#+begin_quote
There is great variation in the degree of certainty with which
measured C-14 samples are associated with the archaeological material
they are intended to date.
#+end_quote

He suggested that archaeologists evaluate the confidence of the
association between dated event and reference event with a four step
scale:
#+attr_latex: :environment inparadesc
 - full certainty, :: the archaeological object itself furnished he
                     measured sample;
 - high probability, :: there is a direct functional relationship
      between the organic material which is measured and the
      diagnostic archaeological finds;
 - probability, :: there is no demonstrable functional relation between
                  measured sample and archaeological material, but the
                  quantity of organic material and the size of the
                  fragments argue in favor of a relationship;
 - reasonable possibility, :: small, scattered fragments.

Waterbolk recommended that samples collected from "brief test
excavations" should not be assigned "high probability."

Although it would be about twenty years until Bayesian techniques were
developed to integrate stratigraphic information into calibration,
Waterbolk clearly pointed to the desirability of combining the two
sources of information.

#+begin_quote
A sounder judgment can be formed of the reliability of a dating if
one has \dots datings of a series of samples from the same vertical
profile.
#+end_quote

**** [cite//b: @harris89:_princ_archaeol_strat]

The Harris matrix was developed to facilitate recording the complex
stratigraphy of urban archaeological sites in Great Britain. It
defines two types of stratigraphic unit---deposits and
interfaces---and sets out a protocol for recording their
characteristics and relationships to one another. Use of the Harris
matrix solves the problems of association and context.

**** [cite//b: @pendergast00:_probl_raised_small_charc_sampl_radioc_analy]

Development of AMS dating greatly reduced the sizes of charcoal
samples required for archaeological dating. This short article points
out potential association and context problems introduced by the
ability to date small pieces of charcoal.

**** [cite//b: @dean78:_indep]

A difficult, highly formalized, paper written when behavioral
archaeology was the rage at the University of Arizona and the author
was active in the Laboratory of Tree Ring Research there. Dean's work
with dendrochronology alerted him early to the difficulties of
archaeological dating.  Distinguishes four meanings of "event" in
archaeological dating, three of which are most useful:
#+attr_latex: :environment inparadesc
  - dated event (E_{d}), :: the event that is actually dated by the
                   laboratory---in radiocarbon dating, this is
                   typically the growth of the plant or the death of
                   the animal that makes up the dating sample;
  - reference event (E_{r}), :: the potentially datable event that can be
      related to the event of interest; and
  - target event (E_{t}), :: the event of archaeological interest.

Develops a terminology to describe relationships among E_{d}, E_{r}, and E_{t}:
#+attr_latex: :environment inparadesc
  - disjunction, :: when E_{d} is older than E_{t};
  - gap, :: when, in a disjunction, E_{d} is older than E_{r};
  - hiatus, :: when, in a disjunction, E_{r} is older than E_{t}; and
  - disparity, :: when E_{d} is younger than E_{t}.

** Substantive Contributions

There are many good examples of radiocarbon dating, but /Gathering
Time/ stands head and shoulders above anything that came before and
has been done since. The main argument is that the kinds of histories
that archaeologists can conceive are shaped by the precision with
which they can measure time.

**** [cite//b: @whittle11:_gather_time]

This two-volume work describes the results of a project to date the
early Neolithic causewayed enclosures of Southern Britain and Ireland.
It is the largest application of the Bayesian approach to modeling
archaeological chronologies ever undertaken. Chapter 2, /Towards/
/generational time-scales: the quantitative interpretation of
archaeological chronologies/, written for "Bayesian virgins,"
describes in detail how the project was able to achieve resolution on
the order of a human generation from archaeological materials more
than 5,000 years old. The best example, from Hambledon Hill,
is described in Chapter 4, /South Wessex/, and should be required
reading for every archaeologist using radiocarbon dating.

** Calibration Software

Calibration software has been available since the mid 1980s.  Software
capable of implementing Bayesian models was introduced around 2000 and
is now widely available.

**** [cite//b: @stuiver86]

One of the first widely available calibration programs, it is
available on the Internet and as a stand-alone application for the
Windows platform. =CALIB= does not support Bayesian models and is thus
somewhat outdated.

**** [cite//b: @buck99:_bcal_internet_arch]

=BCal= is an on-line calibration program designed specifically to
implement Bayesian models. The software follows a step-by-step
procedure that guides the user through data entry and calibration.
Informative context-sensitive help is available at each step. Input
data are stored on the =BCal= server in binary format, which makes
them somewhat difficult to share.  Also, output is restricted to a
(useful) subset of the information generated during the calibration
and might not be sufficient for unusual situations.

**** [cite//b: @bronk01:_devel_of_radioc_calib_progr_oxcal]

=OxCal= is available on the Internet and also as a stand-alone application
that runs in certain versions of the FireFox web browser. It
calibrates individual dates like =CALIB=, and also supports Bayesian
models. =OxCal= is actively developed and supports a wide variety of
models.

* Radiocarbon Dating in Hawaiʻi

Radiocarbon dating has a long history in Hawaiian archaeology, but it
is only recently that it has begun to address the sample composition
and association issues in a meaningful way.

** Overviews

Rob Hommon's experience researching and writing /The Ancient Hawaiian
State/ led him to propose that the Society for Hawaiian Archaeology
set out best practices for radiocarbon dating. Tim Rieth and Steve
Athens at International Archaeological Research Institute put together
a useful programmatic statement, with a focus on sample composition
issues.

**** [cite//b: @rieth13:_sugges_best_pract_applic_radioc]

Sets out "Best Practices" guidelines for acquiring radiocarbon dates.
Distinguishes the dated event from the target event of archaeological
interest and recommends that archaeologists develop a "bridging
argument" that explicitly establishes the chronological relationship
of the two events. Illustrates with a paleontological example from
Barbers Point an interpretive error tied to a naive bridging argument.
Discusses how to select and date wood charcoal, marine shell, bone,
bulk soil, and ash, and recommends that dates on bulk soil and ash be
avoided, if possible. Provides an example tabular report of a
radiocarbon date that does not clearly distinguish the dated event
from the archaeological target event and reports a date on
unidentified material. Table 1 gives lifespans for 32 common Hawaiian
plants as an aid to radiocarbon dating sample selection. Table 2
summarizes the apparent ages of marine shells from Oʻahu, Molokaʻi,
and Hawaiʻi Island. Reports an apparent age, \Delta{}R, of 54 \pm 20 for petrel
bones.

** Sample Composition

The suitability of different sample materials was investigated during
the early years of radiocarbon dating in Hawaiʻi. Unlike other places
in the Pacific, Hawaiian archaeologists have made only limited use of
marine shells for dating and issues surrounding local variations in
the apparent age of the marine environment haven't been fully worked
out. The effects of old wood have been amply documented.

**** [cite//b: @emory69:age_of_sites]

Reports the work of Roy Chatters and Roald Fryxell of the
Radioisotopes and Radiation Laboratory at Washington State University
and Lars Engstrom of the Radiocarbon Laboratory at Stockholm. They
dated a wide variety of materials from the H8 site, including
driftwood, /Cypraea/ shell, sea-urchin spines, fish scales, and fish
bones. Establishes the potentially great age of driftwood that washes
ashore. Concludes that sea urchin spines, fish scales, and fish bones
produce "erratic dates" and are unsuited for radiocarbon dating.
**** [cite//b: @dye00:_effec]

Argues that "old wood" has a demonstrable effect on radiocarbon dates
from Hawaiʻi. Compares the age distribution of 22 dates on identified,
short-lived wood charcoal collected from fire-pits at Bellows Air
Force Station with 22 dates on unidentified wood charcoal mostly
collected from non-feature contexts. Shows that differences in the
distributions are similar to the differences between large samples of
short-lived and long-lived woods dated in New Zealand. Points to three
potential sources of "old wood," including driftwood, waterlogged wood
in alluvial deposits of Puh\amacron{} Stream, and the heartwood of old trees.

**** [cite//b: @dye94:_appar]

Dated 8 marine shells of known age from Bishop Museum collections and
reviewed 11 paired marine shell and wood charcoal dates from the H8
site and sites at Barbers Point, Oʻahu. Identified relatively great
variation in the apparent ages of Hawaiian marine shells and
demonstrated that grazing herbivores from limestone coasts have
apparent ages up to 620 years greater than similar shells from
volcanic coasts. Recommended that archaeological marine shells for
dating should be sourced to a particular local environment and that
the apparent age of shells in that environment should be determined
for best results.

**** [cite//b: @petchey09:_datin_ocean]
Dating marine shells requires that the species be identified and the
dietary and habitat preferences of that species known. Algae grazers
and deposit-feeders aren't suitable for dating because they can ingest
carbon from old limestone or a terrestrial source. Filter-feeders,
typically sessile bivalves, are preferred for dating and will be most
reliable when the bivalves grew in environments with free water
exchange with the open ocean, away from limestone exposures and from
estuaries that carry terrestrial carbon into the ocean.

**** [cite//b: @weisler09:_late_holoc_hawaii_u]

Using paired U-series and radiocarbon dates on twelve pieces of
/Pocillopora/ sp. branch coral from various locations on Molokaʻi
Island, establishes that the apparent age of the marine environment of
southern Molokaʻi did not vary spatially in the seventeenth century
and that it was also consistent over the period AD 700--1800.

** Association and Context

Nowadays, discussions of association and context are carried out in
the context of Bayesian calibration.

**** [cite//b: @dye10:_tradit_hawaiian]

An attempt to introduce Bayesian calibration to Hawaiian
archaeologists. Develops and illustrates a simple Bayesian model that
can be used to estimate the construction date of a surface
architectural feature. Describes a set of field procedures to support
the data requirements of the model and recommends they be applied
generally in Hawaiʻi. Proposes a dynamic settlement pattern
hypothesis: "There are two components to the diachronic settlement
pattern of traditional Hawaiʻi, with a fixed set of temple structure
locations surrounded by a more transient set of habitation
structures."

** Substantive Contributions

The changes brought about by archaeologists paying attention to sample
composition, association, and context are most easily seen in the
changing estimates for the age of early sites and estimates for
Polynesian settlement of Hawaiʻi. The firewood contents of fire-pits
can be precisely located in both space and time---they provide a
unique data set with great potential for interpretation.

*** Early Sites

The three sites thought to represent early settlement are now thought
to date several hundred years later than the initial estimates.

**** [cite//b: @dye92:_south_point]

Uses an ad hoc graphical technique to estimate the duration of time
represented by individual layers at the H1 and H8 sites. Concludes
that the duration of Layer II at the H8 site was about 1,000 years,
from the late seventh century to about AD 1650, and that the duration
of Layer I at H8 was about 200 years, from AD 1650 to site abandonment
around AD 1850. Also concludes that Layers III and II at H1 were both
deposited in the first half of the fifteenth century. Favorably
compares these results to a cross-dating of the sites based on the
relative frequencies of one-piece fishhook head types 1A, 1B, and 4.

**** [cite//b: @kirch07:_recon_hawaiian_cultur_sequen]

Reports radiocarbon dates on three pieces of bone and three carbonized
twigs collected from non-feature contexts at the Halawa Dune Site,
Molokaʻi. Concludes that the site was unlikely to have been settled
prior to AD 1300, some seven to eight centuries later than initially
estimated. "Old wood" and problematic procedures at the dating
laboratory are thought to have contributed to anomalously early age
estimates.

**** [cite//b: @dye10:_age_o18_site_hawaii]

Seven new radiocarbon age determinations indicate that the O18 site
was established in AD 1040--1219, quite a bit later than previous
estimates of the seventh, fourth, and eighth centuries AD. Implicates
the effects of dating "old wood" as one reason for the erroneously old
age estimates.

*** Polynesian Settlement
Archaeologists are naturally interested in "firsts." The date
Polynesians discovered and settled Hawaiʻi has pride of place as the
first of the firsts.
**** [cite//b: @emory28:_archaeol_nihoa_necker_islan]
Before radiocarbon dating, the settlement date was estimated with
genealogical records, using an average generation length of 25 years.

**** [cite//b: @sinoto70:_archaeol_based_asses_of_marques]
An estimate based on work at South Point and the Marquesas.

**** [cite//b: @bellwood79:conquest]
Hawaiʻi settlement as seen from the context of Oceania and Southeast
Asia.

**** [cite//b: @kirch85:_feath_gods_fishh]
The classic textbook of Hawaiian archaeology. Argues from a
consideration of "early" sites and comparisons with dates from the
Eastern Polynesian homeland.

**** [cite//b: @hunt91:_hawaiian_islan]

The earliest estimate of Polynesian settlement, based on a
consideration of a large corpus of radiocarbon dates, few of which
controlled for sample composition or association and context.

**** [cite//b: @spriggs93:_late_east_polyn]

Chronometric hygiene scrubs away many early dates, yielding a "late"
chronology.

**** [cite//b: @graves95:_polyn_settl_of_hawaiian_archip]

Another plea for the usefulness of the early dates, this time based on
the idea that settlement was a multi-stage process.

**** [cite//b: @athens97:_historical_ecology]

Introduces paleoenvironmental data into the discussion of Polynesian
settlement. These date point to a substantially later settlement than
most Hawaiian archaeologists at the time were prepared to entertain.

**** [cite//b: @kirch00:_road_winds]
Kirch's "Bellwood book" begins to express some doubt about the early
Hawaiian sites, but doesn't yet fully appreciate the
paleoenvironmental data reported by [cite//b: @athens97:_historical_ecology]

**** [cite//b: @wilmshurst11:_high_east_polyn]

Radical chronometric hygiene yields really late estimates for
settlement of East Polynesia, including Hawaiʻi. Contrast the
settlement estimate derived after chronometric hygiene with the
unhygienic estimate proposed by [cite//b: @hunt91:_hawaiian_islan], which is about a
millennium older.

**** [cite//b: @kirch11:_when_polyn_hawaii]

Reviews and summarizes the history of ideas relating to the timing of
the settlement of Hawaiʻi; brings together the latest information,
including the chronology of settlement for the Central East Polynesia
region, paleoenvironmental proxy records from Oʻahu and Kauaʻi, dates
obtained from bones of the Polynesian-introduced rat, and the
re-dating of Site O18.

**** [cite//b: @rieth11:_centur_polyn_colon_hawaii_islan]

Compiles 926 radiocarbon dates from Hawaiʻi Island and classifies them
according to sample material and the precision reported by the dating
laboratory.  Table 1 provides a list of short-lived and long-lived
taxa commonly used as radiocarbon dating samples in Hawaiʻi.

**** [cite//b: @dye11:_model_age_estim_polyn_colon_hawaii]

A model-based Bayesian calibration using radiocarbon data from
paleoenvironmental cores and materials introduced to the islands by
Polynesian colonists estimates that the islands were likely colonized
sometime late in the first millennium AD. Two calibrations, one using
radiocarbon dates on floral materials and the other using radiocarbon
dates on floral and faunal materials, indicate that archaeological
materials yield relatively imprecise estimates of the colonization
event with 95 percent highest posterior density regions 3–5 centuries
long.

**** [cite//b: @athens14:_paleoen_archaeol_model_based_age]

Augments [cite//b: @dye11:_model_age_estim_polyn_colon_hawaii], with additional data from the pre-colonization and
post-colonization periods. Derives a more precise estimate of the
settlement date in the eleventh century AD. Supports this estimate
with a similar age estimate derived from an age-depth model applied to
a paleoenvironmental core from Ordy Pond on Oʻahu.

*** Firewood Use

**** [cite//b: @dye13:_chang_patter_firew_use_waiman_plain;] 
Wood charcoal identifications from 35 dated traditional Hawaiian
fire-pits on the Waim\amacron{}nalo Plain are analyzed for evidence of change
over time and difference across space. Plant taxa identified in the
firewood are classified according to habit, origin, and elevational
distribution. Early in traditional Hawaiian times, firewood was
commonly brought to the plain from inland forests and fires were made
primarily with native plants. Later, firewood was more likely to be
collected locally, and it typically included both
Polynesian-introduced and native plants. This change in behavior
appears to have taken place in the fifteenth century. It was likely
associated with a vegetation change in which the native lowland
forest was replaced with a variety of useful plants, especially near
Puh\amacron{} Stream.

#+print_bibliography:

* Instructions for Use                                             :noexport:
  :PROPERTIES:
  :EXPORT_TITLE: Annotated Bibliography Template
  :EXPORT_OPTIONS: tags:nil todo:nil
  :EXPORT_AUTHOR: Thomas S. Dye
  :EXPORT_FILE_NAME: anno-bib-template-worg
  :END:
** Introduction
This file describes a template for creating an annotated bibliography
document using Org mode. The document is intended to be output as a
pdf file and distributed as printed hard copy.

The template is distributed as =annotated-biblio-template.org= at
https://github.com/tsdye/org-bib-template.git.

An example of its use can be found in the files =14c-workshop.org= and
=local.bib=, also at https://github.com/tsdye/org-bib-template.git.

The goal was to design a template that makes an annotated bibiliography
  - easy to build,
  - good looking, and
  - organized by topical sections and subsections.

The template relies on a working LaTeX installation that includes several common
LaTeX packages, and, optionally, a bibliography database manager for Emacs
(table [[software-requirements]]).

#+name: software-requirements
#+caption[Open source software used by the template]: *Open source software used by the template*
| Software        | Distribution      | Installation                                |
|-----------------+-------------------+---------------------------------------------|
| LaTeX           | [[http://www.tug.org/texlive][TeX Live (Linux)]]  | See distribution instructions               |
|                 | [[http://www.tug.org/mactex/][MacTeX (Mac OS X)]] | See distribution instructions               |
|                 | [[http://www.tug.org/protext/][proTeXt (Windows)]] | See distribution instructions               |
| LaTeX packages  | [[http://www.ctan.org/pkg/biblatex][biblatex]]          | Typically included with LaTeX distributions |
|                 | [[http://www.ctan.org/pkg/koma-script][scrartcl]]          | Typically included with LaTeX distributions |
|                 | [[http://www.ctan.org/pkg/paralist][paralist]]          | Typically included with LaTeX distributions |
|                 | [[http://ctan.org/tex-archive/macros/latex/contrib/microtype][microtype]]         | Typically included with LaTeX distributions |
|                 | [[http://www.ctan.org/pkg/tex-gyre][tex-gyre]]          | Typically included with LaTeX distributions |
| [[http://joostkremers.github.io/ebib/][Ebib]] (optional) | [[http://melpa.milkbox.net/#/][MELPA]]             | Path set up by ELPA                         |

In the Org mode file, the first three heading levels are reserved for
topics and sub-topics. Bibliographic entries are placed on fourth
level headings. 

#+name: first-eg
#+begin_example
,* Topic
,** Sub-topic
,*** Sub-sub-topic
,**** [cite//b: @stuiver86]
#+end_example

** Workflow
First, you should set the =#+TITLE:=, =#+AUTHOR:=, =#+EMAIL:=, and =#+EXPORT_FILE_NAME=
options at the top of the buffer.

#+begin_example
,#+TITLE: Your Title
,#+AUTHOR: Your Name
,#+EMAIL: Your email
,#+EXPORT_FILE_NAME: Your file name
#+end_example

The other options at the top of the buffer assume the bibliographic database is named =local.bib= and that it resides somewhere LaTeX can find it, and that the annotated bibliography will be printed single sided on letter paper.  These other options are described [[*Options and Keywords][below]], in case you want to change them.

I like to organize my annotated bibliographies the same way I've learned to
organize projects in Org mode; I make an outline of topics and subtopics using
first, second, and third level headings as necessary. Then I write whatever
comes to mind for each of the headings. From then on, I insert bibliographic
entries as fourth level headings, annotate them, and revise topic and sub-topic
text accordingly.

Bibliographic entries are inserted as fourth level headings,
regardless of the heading level immediately preceding them.  Thus, the
following example will work just as well as the [[first-eg][earlier example]]:

#+name: second-eg
#+begin_example
,* Topic
,**** [cite//b: @stuiver86]
#+end_example

Over the years, my colleagues and I have created a master bibliography with more
than 4,000 entries. This is a bit unwieldy to distribute, so I like to make a
local bibliography that only contains the entries that appear in the annotated
bibliography and that can be easily distributed. One way to do this, and the way
that I prefer, is to create a [[http://joostkremers.github.io/ebib/ebib-manual.html#main-and-dependent-databases][dependent database]] in [[http://joostkremers.github.io/ebib/][Ebib]] and then add entries to
it with =M-x ebib-insert-citation= as the annotated bibliography is being
written. Adding an entry to the annotated bibliography involves creating the
fourth level headline and then inserting a citation with the default style and
bare variant, =[cite//b: ...]=, which corresponds with the [[https://www.ctan.org/pkg/biblatex][BibLaTeX]] =cite=
command. I do this with Ebib, as outlined below, but in practice you are free to
use whatever method suits you. Once that is done you should have an Org citation
as a fourth level headline, leaving you ready to annotate.

When you are finished adding annotated entries, then export the buffer to LaTeX in the usual way.
** Options and Keywords

The following example of options and keywords is one that I used
for an annotated bibliography of radiocarbon dating in
Hawaiʻi. The =#+OPTIONS:= line lists options in order of descending
importance. The option =h:4= ensures that headings include LaTeX
paragraphs, which are used to typeset the bibliographic entries. The
option =toc:3= puts all headings above the bibliographic entries into
the table of contents. Depending on how much detail you want in the
table of contents, this could sensibly be set to =toc:2= or =toc:1=.
Or, for a simple bibliography, even =toc:nil=.  The options =tags:nil=
and =todo:nil= ensure that none of the Org mode metadata attached to
headings makes it into the exported document. The last two options are
useful for LaTeX export; I like =^:{}= because my [[https://www.bibtex.org/Using/][BibTeX]] keys are
configured to use underscores and I don't want parts of the keys
rendered in the Org mode buffer as underscores.

#+begin_example
,#+name: ante-matter
,#+begin_example
,,#+OPTIONS: h:4 toc:3 tags:nil todo:nil ':t ^:{}
,,#+LATEX_CLASS: anno-bib-times
,,#+LATEX_CLASS_OPTIONS: [paper=letter,oneside,DIV=8]
,,#+LATEX_HEADER: \usepackage[style=verbose,backend=biber]{biblatex}
,,#+LATEX_HEADER: \addbibresource{local.bib}
,,#+BIBLIOGRAPHY: local.bib
,,#+CITE_EXPORT: biblatex verbose
,,#+STARTUP: entitiespretty
,#+end_example
#+end_example

The =#+LATEX_CLASS:= keyword needs to match the class name defined
[[*The Org LaTeX Class][below]].

The =#+LATEX_CLASS_OPTIONS:= keyword can take any option described in
the [[http://www.ctan.org/pkg/koma-script][Koma Script]] manual. The options shown in the example: set the paper
size to letter paper (Europeans might want to use =a4= here, or simply
get rid of the option to use the default, which is =a4=); formats for
single-sided output, which is good for a bibliography that will be
bound with a staple at the top left corner; and uses =DIV= to
calculate the type area of the page.  Longer and more complex
bibliographies that will be distributed with a binding might want to
use the =twoside= option. The integer value of the =DIV= option
determines the size of the type area; larger integers increase the
size of the type area.

The two =#+LATEX_HEADER:= keywords are included here, rather than in
the definition of =anno-bib-times=, because they are likely to change from
one annotated bibliography to the next.  In general, the [[https://www.ctan.org/pkg/biblatex][BibLaTeX]]
package will always use the =verbose= style, but the backend will
depend on which of [[https://www.bibtex.org/Using/][BibTeX]] or [[https://biblatex-biber.sourceforge.net/][Biber]] you are accustomed to using.  The
second =#+LATEX_HEADER= specifies the name of the bibliographic
database that holds entries for the works that appear in the annotated
bibliography.

The last line, which starts up Org mode with =entitiespretty= is just
a personal preference for the look of the buffer.

** LaTeX Process
The Org mode variable =org-latex-pdf-process= holds a list of strings, each of
which is run as a shell command. Typically, several commands are needed to
process a LaTeX document to produce pdf output. The following source code block
uses a straightforward approach that should work in most cases. The source code
block named =anno-bib-biber= uses a bibliography processor named [[http://biblatex-biber.sourceforge.net/][Biber]], which is
designed to work with [[http://www.ctan.org/pkg/biblatex][BibLaTeX]]. If you use the BibTeX processor, then this
choice must be reflected in the =usepackage= command for [[https://www.ctan.org/pkg/biblatex][BibLaTeX]] at the top of
this file; the optional command =backend= takes either =bibtex= or =biber= as
its value. At a practical level, perhaps the main difference between [[https://biblatex-biber.sourceforge.net/][Biber]] and
[[https://www.bibtex.org/Using/][BibTeX]] is how they handle special characters. The bibliographic
database for [[https://www.bibtex.org/Using/][BibTeX]] uses LaTeX commands for special characters while
the database for [[https://biblatex-biber.sourceforge.net/][Biber]] can also use UTF-8 characters.

#+begin_example
,#+name: anno-bib-biber
,#+header: :results silent
,#+begin_src emacs-lisp
  (setq org-latex-pdf-process
        '("lualatex -interaction nonstopmode -output-directory %o %f"
          "biber %b"
          "lualatex -interaction nonstopmode -output-directory %o %f"
          "lualatex -interaction nonstopmode -output-directory %o %f"))
,#+end_src
#+end_example

#+name: anno-bib-biber
#+header: :results silent :exports none
#+begin_src emacs-lisp
  (setq org-latex-pdf-process
        '("lualatex -interaction nonstopmode -output-directory %o %f"
          "biber %b"
          "lualatex -interaction nonstopmode -output-directory %o %f"
          "lualatex -interaction nonstopmode -output-directory %o %f"))
#+end_src

The LaTeX process also uses the TeX engine, [[https://www.luatex.org/][LuaLaTeX]], which is UTF-8 aware.  An alternative here might be [[https://tug.org/xetex/][XeLaTeX]].

** Citations
There are many ways to manage citations in Org mode and you are free to use your
own way. My preference is to manage the bibliography database with [[http://joostkremers.github.io/ebib/][Ebib: a
BibTeX database manager for Emacs]] and use its facilities to insert citations.
The source code block named =ebib-setup= defines a =cite= command that [[http://joostkremers.github.io/ebib/][Ebib]] will
use to insert citations in an Org mode buffer. Note that if you have already set
=ebib-citation-commands= this source code block will override your settings.
If you would like to preserve your settings, then remove the corresponding line
in the local variables at the bottom of this file.

#+begin_example
,#+name: ebib-setup
,#+header: :results silent :exports none
,#+begin_src emacs-lisp
  (setq ebib-citation-commands
        '((any (("cite" "\\cite%<[%A]%>{%K}")))
          (org-mode (("autocite" "[cite: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("autocites" "[cite: %<%A %>%(%<%A %>@%K%< %A%>%< %A%>;%)%< %A%>]")
                     ("autocite*" "[cite/na: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("fullcite" "[cite/full: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("multicite" "%<%A %>@%K%< %A%>%< %A%>;")
                     ("notecite" "[cite/l/b: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Notecite" "[cite/l/bc: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Pnotecite" "[cite/l/c: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("pnotecite" "[cite/l: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("textcite" "[cite/t: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("textcites" "[cite/t: %<%A %>%(%<%A %>@%K%< %A%>%< %A%>;%)%< %A%>]")
                     ("Textcite" "[cite/t/c: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("citeauthor" "[cite/a/f: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("citeauthor*" "[cite/a: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Citeauthor" "[cite/a/cf: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Citeauthor*" "[cite/a/c: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("citeyear" "[cite/na: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("cite" "[cite//b: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Cite" "[cite//bc: %<%A %>@%K%< %A%>%< %A%>;]"))))
,#+end_src
#+end_example

#+name: ebib-setup
#+header: :results silent :exports none
#+begin_src emacs-lisp
  (setq ebib-citation-commands
        '((any (("cite" "\\cite%<[%A]%>{%K}")))
          (org-mode (("autocite" "[cite: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("autocites" "[cite: %<%A %>%(%<%A %>@%K%< %A%>%< %A%>;%)%< %A%>]")
                     ("autocite*" "[cite/na: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("fullcite" "[cite/full: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("multicite" "%<%A %>@%K%< %A%>%< %A%>;")
                     ("notecite" "[cite/l/b: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Notecite" "[cite/l/bc: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Pnotecite" "[cite/l/c: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("pnotecite" "[cite/l: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("textcite" "[cite/t: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("textcites" "[cite/t: %<%A %>%(%<%A %>@%K%< %A%>%< %A%>;%)%< %A%>]")
                     ("Textcite" "[cite/t/c: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("citeauthor" "[cite/a/f: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("citeauthor*" "[cite/a: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Citeauthor" "[cite/a/cf: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Citeauthor*" "[cite/a/c: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("citeyear" "[cite/na: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("cite" "[cite//b: %<%A %>@%K%< %A%>%< %A%>;]")
                     ("Cite" "[cite//bc: %<%A %>@%K%< %A%>%< %A%>;]"))))
#+end_src
** The Org LaTeX Class
The following source code block sets up a LaTeX class, =anno-bib-times=, that can be used to typeset the annotated bibliography. The LaTeX class defined here must be referenced in the =#+LATEX_CLASS= option near the top of the buffer. The
=anno-bib-times= class is based on the [[http://www.ctan.org/pkg/koma-script][Koma script]] article class
=scrartcl=, which uses a sans-serif font for headings and a serif font
for body text.

The =anno-bib-times= class uses fonts from the [[http://www.gust.org.pl/projects/e-foundry/tex-gyre/][TeX Gyre collection of fonts]]. As
explained in [[http://www.gust.org.pl/projects/e-foundry/tex-gyre/tb87hagen-gyre.pdf][The New Font Project: TeX Gyre]], a goal of the project was to
produce good quality fonts with diacritical characters sufficient to cover all
European languages as well as Vietnamese and Navajo.

The source code block named =anno-bib-times= is based on the Times Roman font.
The serif Termes font is a replacement for Times Roman, the sans-serif Heros
font is a replacement for Helvetica, and the typewriter Cursor font is a
replacement for Courier. The [[https://www.gust.org.pl/projects/e-foundry/tex-gyre/][Tex Gyre]] fonts benefit from the [[http://ctan.org/tex-archive/macros/latex/contrib/microtype][microtype package]],
which provides "subliminal refinements towards typographical perfection,"
including "character protrusion and font expansion, furthermore the adjustment
of inter-word spacing and additional kerning, as well as hyphenatable letter
spacing (tracking) and the possibility to disable all or selected ligatures."

In addition, the [[http://www.ctan.org/tex-archive/macros/latex/contrib/paralist/][paralist package]] is used for its compact versions of
the LaTeX list environments.

The several lines devoted to specifying a new Unicode character add a glyph for the glottal stop from Hawaiian orthography.

Finally, the =newcommand= is provided as an illustration of one
way to move LaTeX declarations out of the Org file header. This one is
useful in my work as an archaeologist and over the years it has crept
into my [[https://www.bibtex.org/Using/][BibTeX]] database. It shouldn't interfere with your work, but
you might want to remove it or replace it with LaTeX commands that you
do frequently use.

#+begin_example
,#+name: anno-bib-times
,#+header: :results silent :exports none
,#+begin_src emacs-lisp
  (require 'ox-latex)
  (add-to-list 'org-latex-classes
               '("anno-bib-times"
                 "\\documentclass{scrartcl}
                 [NO-DEFAULT-PACKAGES]
                 [PACKAGES]
                 [EXTRA]
                  \\usepackage{microtype}
                  \\usepackage{fontspec}
                  \\defaultfontfeatures{Ligatures=TeX}
                  \\setmainfont{TeX Gyre Termes}
                  \\setsansfont{TeX Gyre Heros}[Scale=MatchLowercase]
                  \\setmonofont{TeX Gyre Cursor}[Scale=MatchLowercase]
                  \\usepackage{paralist}
                  \\usepackage{graphicx}
                  \\usepackage[x11names]{xcolor}
                  \\usepackage[colorlinks=true,allcolors=Blue4]{hyperref}
                  \\usepackage{newunicodechar}
                  \\DeclareRobustCommand{\\ookina}{%
                  \\raisebox{\\dimexpr\\fontcharht\\font`A-\\height}{%
                  \\scalebox{0.8}{`}%
                         }%
                      }%
                  \\newunicodechar{ʻ}{\\ookina}
                  \\newcommand{\\rc}{$^{14}C$}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
,#+end_src
#+end_example

#+name: anno-bib-times
#+header: :results silent :exports none
#+begin_src emacs-lisp
  (require 'ox-latex)
  (add-to-list 'org-latex-classes
               '("anno-bib-times"
                 "\\documentclass{scrartcl}
                 [NO-DEFAULT-PACKAGES]
                 [PACKAGES]
                 [EXTRA]
                  \\usepackage{microtype}
                  \\usepackage{fontspec}
                  \\defaultfontfeatures{Ligatures=TeX}
                  \\setmainfont{TeX Gyre Termes}
                  \\setsansfont{TeX Gyre Heros}[Scale=MatchLowercase]
                  \\setmonofont{TeX Gyre Cursor}[Scale=MatchLowercase]
                  \\usepackage{paralist}
                  \\usepackage{graphicx}
                  \\usepackage[x11names]{xcolor}
                  \\usepackage[colorlinks=true,allcolors=Blue4]{hyperref}
                  \\usepackage{newunicodechar}
                  \\DeclareRobustCommand{\\ookina}{%
                  \\raisebox{\\dimexpr\\fontcharht\\font`A-\\height}{%
                  \\scalebox{0.8}{`}%
                         }%
                      }%
                  \\newunicodechar{ʻ}{\\ookina}
                  \\newcommand{\\rc}{$^{14}C$}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}")))
#+end_src

** Local variables

The [[local-vars-eg][local variables]] call the source code blocks defined earlier to set
up the export environment. When the file
=annotated-biblio-template.org= is opened, Emacs will prompt to allow
the local variables to be executed.

The first call sets up the Org LaTeX class with Times New Roman as the serif
font. The second call sets up the Org mode pdf process to use the [[https://www.luatex.org/][LuaLaTeX]] engine
and [[https://biblatex-biber.sourceforge.net/][Biber]]. The final call sets up [[http://joostkremers.github.io/ebib/][Ebib]] to insert citations into the Org mode
buffer.  You should remove this final line if you are using another method to work with bibliographies.

#+name: local-vars-eg
#+begin_example
# eval: (org-sbe "anno-bib-times")
# eval: (org-sbe "anno-bib-biber")
# eval: (org-sbe "ebib-setup")
#+end_example

* Quotes about Radiocarbon Revolution                              :noexport:

Alex Bayliss, an archaeologist and dating expert at English Heritage,
said: "The dates were not what we expected when we began this project
but prehistorians are just going to have to get their heads around it,
a lot of what we have been taught in the past is complete bollocks."
Bayliss worked on the new dating system with Professor Alasdair
Whittle of Cardiff University and other experts, combining hundreds of
thousands of scraps of dating evidence, obtained from the last century
of excavations, on Cardiff's computers. They matched notoriously
imprecise carbon-14 dates from organic remains – which can have a
margin of error of centuries – with all the other evidence from
archaeological finds, narrowing the dates for sites from centuries to
decades. "The old techniques gave us such imprecise results that it's
like taking the Napoleonic wars, the first world war, the second world
war and the computer revolution and insisting that they're all
contemporary. "Now we can narrow that down dramatically. You take a
granny with a good long life living near Windmill Hill in Avebury, she
could have seen her family start the enclosure as a child, see it fall
out of fashion and them turn to building barrows, and then return to
do more work on the enclosure, all in her lifetime."

* Talk Outline                                                     :noexport:
  :PROPERTIES:
  :EXPORT_FILE_NAME: talk-outline
  :EXPORT_OPTIONS: toc:nil tags:nil
  :END:
 1. Thanks
    1. Holly and Mara from the SHA Board
    2. Others who helped with the pizza and beer
 2. Overview
    1. Glad to see such interest in radiocarbon dating
    2. Fun putting together the slide show
    3. If you have questions, raise a hand or note the slide number
 3. Radiocarbon revolution: Three phases
    1. Alex Bayliss, p. 3
    2. Alasdair Whittle, Gathering Time, p. 6
 4. Thinking Clearly
    1. Jeff Dean, p. 5
    2. H. T. Waterbolk, p. 4
    3. Bowman, p. 2, best overview
    4. Taylor, p. 2, most thorough overview
 5. Thinking Clearly diagram
    1. E_{t} = Target event
    2. E_{r} = Reference event
    3. E_{d} = Dated event
 6. Example 1 is fictitious
 7. Example 2 is also fictitious
 8. Sample Composition
    1. Rieth and Athens, /Hawaiian Archaeology/, p. 7
    2. Dye (2000) /Radiocarbon/, p. 8
 9. Sample Composition, Marine Shell
    1. Rieth and Athens, /Hawaiian Archaeology/, p. 7
    2. Dye (1994) /Radiocarbon/, p. 8
 10. Sample Composition, Marine Shell
     1. Petchey, p. 9
 11. Association and Context
     1. Harris, p. 5, for context and matrix
     2. Waterbolk, p. 4, for association
     3. Taylor, p. 2 has a good overview
 12. Polynesian Settlement
     1. Dye (2011), p. 12
     2. Athens, Rieth and Dye (2014), p. 13
 13. Polynesian Settlement
     1. References on p. 10--12
     2. Early sites, p. 10
 14. Dynamic Settlement Pattern
     1. Roger Green's idea
     2. Surface Architecture, p. 9
 15. Dynamic Settlement Pattern graph
     1. Sample composition and association from older contexts
 16. Dynamic Settlement Pattern
     1. Requires Bayesian calibration software
     2. BCal Buck, Christen and James, p. 6
     3. OxCal, Ramsey p. 7
     4. Calib won't do, Reimer, p. 6
 17. Firewood Choice
     1. Dye and Sholin, p. 13
     2. Unique circumstances---an event, precisely located in space
        and time.
* Local variables                                                  :noexport:

# Local Variables:
# eval: (org-sbe "anno-bib-times")
# eval: (org-sbe "anno-bib-biber")
# eval: (org-sbe "ebib-setup")
# End:
